CREATE TABLE "books" (
	"book_id" text PRIMARY KEY NOT NULL,
	"title" varchar(200) NOT NULL,
	"word_count" integer DEFAULT 0 NOT NULL,
	"cover_url" text NOT NULL,
	"tags" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "books_word_count_check" CHECK ("books"."word_count" >= 0)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "words" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "words_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"wordRank" integer,
	"headWord" text,
	"content" json,
	"bookId" text
);
--> statement-breakpoint
INSERT INTO "books" ("book_id", "title", "word_count", "cover_url", "tags")
SELECT
	"bookId",
	"bookId",
	count(*)::integer,
	'/book-cover-placeholder.svg',
	ARRAY[]::text[]
FROM "words"
WHERE "bookId" IS NOT NULL
GROUP BY "bookId"
ON CONFLICT ("book_id") DO NOTHING;
--> statement-breakpoint
ALTER TABLE "words" ADD CONSTRAINT "words_bookId_books_book_id_fk" FOREIGN KEY ("bookId") REFERENCES "public"."books"("book_id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "books_updated_at_idx" ON "books" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX "words_book_id_idx" ON "words" USING btree ("bookId");
