-- Formalize credential users, add sequential learning progress, and strengthen
-- the existing books/words catalog. This migration is additive and keeps the
-- legacy public."User" table name used by the starter's authentication code.

create table if not exists public."User" (
  id serial primary key,
  email varchar(254),
  password varchar(255),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public."User"
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now();

alter table public."User"
  alter column email type varchar(254),
  alter column password type varchar(255);

update public."User"
set email = lower(btrim(email))
where email is not null
  and email <> lower(btrim(email));

do $$
begin
  if exists (
    select 1
    from public."User"
    where email is null
       or nullif(btrim(email), '') is null
       or password is null
       or nullif(password, '') is null
  ) then
    raise exception 'Cannot migrate "User": null or empty email/password rows exist';
  end if;

  if exists (
    select 1
    from public."User"
    group by lower(email)
    having count(*) > 1
  ) then
    raise exception 'Cannot migrate "User": duplicate normalized emails exist';
  end if;
end
$$;

alter table public."User"
  alter column email set not null,
  alter column password set not null;

create unique index if not exists user_email_lower_unique
  on public."User" (lower(email));

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'books_word_count_nonnegative'
      and conrelid = 'public.books'::regclass
  ) then
    alter table public.books
      add constraint books_word_count_nonnegative
      check (word_count >= 0) not valid;
  end if;
end
$$;

alter table public.books
  validate constraint books_word_count_nonnegative;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'words_book_fk'
      and conrelid = 'public.words'::regclass
  ) then
    alter table public.words
      add constraint words_book_fk
      foreign key ("bookId")
      references public.books (book_id)
      on update cascade
      on delete cascade
      not valid;
  end if;
end
$$;

alter table public.words
  validate constraint words_book_fk;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'words_rank_positive'
      and conrelid = 'public.words'::regclass
  ) then
    alter table public.words
      add constraint words_rank_positive
      check ("wordRank" is null or "wordRank" > 0) not valid;
  end if;
end
$$;

alter table public.words
  validate constraint words_rank_positive;

create index if not exists words_book_rank_id_idx
  on public.words ("bookId", "wordRank", id);

create unique index if not exists words_book_word_id_unique
  on public.words (
    "bookId",
    ((content -> 'word' ->> 'wordId'))
  )
  where
    "bookId" is not null
    and nullif(btrim(content -> 'word' ->> 'wordId'), '') is not null;

create table if not exists public.learning_progress (
  id bigint generated by default as identity primary key,
  user_id integer not null,
  book_id text not null,
  last_word_row_id bigint null,
  last_word_rank integer null,
  learned_count integer not null default 0,
  total_words integer not null,
  status text not null default 'learning',
  version integer not null default 0,
  started_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  completed_at timestamp with time zone null,

  constraint learning_progress_user_fk
    foreign key (user_id)
    references public."User" (id)
    on delete cascade,

  constraint learning_progress_book_fk
    foreign key (book_id)
    references public.books (book_id)
    on update cascade
    on delete cascade,

  constraint learning_progress_last_word_fk
    foreign key (last_word_row_id)
    references public.words (id)
    on delete set null,

  constraint learning_progress_user_book_unique
    unique (user_id, book_id),

  constraint learning_progress_status_check
    check (status in ('learning', 'completed')),

  constraint learning_progress_count_check
    check (
      total_words > 0
      and learned_count >= 0
      and learned_count <= total_words
    ),

  constraint learning_progress_rank_check
    check (
      (learned_count = 0 and last_word_rank is null)
      or (learned_count > 0 and last_word_rank is not null)
    ),

  constraint learning_progress_completion_check
    check (
      (
        status = 'learning'
        and learned_count < total_words
        and completed_at is null
      )
      or
      (
        status = 'completed'
        and learned_count = total_words
        and completed_at is not null
      )
    )
);

create index if not exists learning_progress_user_updated_idx
  on public.learning_progress (user_id, updated_at desc);

create index if not exists learning_progress_recent_learning_idx
  on public.learning_progress (user_id, updated_at desc)
  where status = 'learning';

